### ISSUE TITLE
sleep isn't working

### ISSUE THREAD

**Issue by ghost** [WhiteUser/N552VWHackintosh#1]
Hello
I have the same laptop , my sleep isn't working (instant wake), how about you?

**Comment by walkerfirmin** [comment]
I didn’t do any patches to enable sleep it just worked but I disabled it because it was messing with my sound in Mojave even with codec commander kext

**Comment by ghost** [comment]
My English isn't good but I try to say my words
I have removed battery maybe that is the reason for sleep
I used this method for enabling sound :
1. apply patch : audio layout 3
2. delete AppleHDA.kext from /System/Library/Extensions
2. install these two kexts that I attached 

[sound.zip](https://github.com/WhiteUser/N552VWHackintosh/files/2457018/sound.zip)

I have another problem with my HDD it's making noise each 2 or 3 minutes once 
also you can use my Clover Folder , everything is working(brightness, sound, touchpad, ...) but sleep 
[Clover.zip](https://drive.google.com/file/d/1ifAHbHTfyJutKVFiEgDllNN2_OdDgk_L/view?usp=sharing)

**Comment by walkerfirmin** [comment]
That is not the method I described for Mojave and the method I described for High Sierra does use layout id 3 and it uses up-to-date versions of the provided kexts, but it does not involve touching the AppleHDA.kext. You need the original untouched AppleHDA.kext for this to work

**Comment by walkerfirmin** [comment]
And hards drives make noise no matter what that just means it is working and not powered off for sleep. Are you using Mojave or something else?

**Comment by ghost** [comment]
Thank you for your reply 
I'm using Mojave and sound is working fine with touched AppleHDA

**Comment by ghost** [comment]
But HDD isn't making noise on windows 10
